### PR TITLE
Do not show routes on Permissions list when advanced config is enabled

### PR DESCRIPTION
**Pull request by re3lex**
fix for issue described in this comment 
https://github.com/mdmsoft/yii2-admin/pull/309#issuecomment-431476844

### CODE REVIEW

**Comment by nomaanp** [comment]
@mdmunir @sihar any update for this pull request?

**Comment by sihar** [comment]
Sorry, for late response. I never use advanced config before.
I will test it in idle time. 
Btw, you may test this PR and give your opinion  :D

**Comment by nomaanp** [comment]
Hi @sihar ,
I checked this changes and it is removing the routes from the permission page. I'm attaching the screenshot from @re3lex master and feature branch. Please take a look at it.

master branch(Issue):
image

feature branch (Fixed):
image

**Comment by nomaanp** [comment]
> Hi @sihar ,
> I checked this changes and it is removing the routes from the permission page. I'm attaching the screenshot from @re3lex master and feature branch. Please take a look at it.
> 
> master branch(Issue):
> image
> 
> feature branch (Fixed):
> image

@sihar any update?

**Comment by sihar** [comment]
thanks for your effort @nomaanp  
I test this PR too and it works

**Pull request merged**
