### PR TITLE
Small enhancements on the Assignment pages

### PR DESCRIPTION
**Pull request by softark**
1. assignment/view page is now able to show the full name of the user that might be retrieved from a related model.
2. assignment/index page is now able to show extra information of the user like full name, position in the organization, etc that might be stored in the related model.

I'm not sure if you like it or not, because this kind of enhancement may break the simpleness of this extension. In fact, I don't want it to be a complicated, heavily featured, overly designed "user management system". So, I tried to make these enhancements optional.

### CODE REVIEW

**Comment by softark** [comment]
screen shot of the index page
auth

**Comment by softark** [comment]
In a project of mine, I had to write a module for user management.

I created a table called "staff" and stored the information for authentication in it: "id", "staff_no" and "password".
"staff_no" is a 4-digit unique number that identifies the staff in a company, and the users are to use "employee_no" and "password" to login to the system.

And I also had to have detailed information about the staff.
What is his/her full name in Japanese and/or Chinese character? Which department does he/she belong to? What is his/her profession? ... etc.
I decided to store all those information not in "staff" table but in "profile" table and its related tables like "dept" and "job".

I didn't want to implement the auth management module from the scratch. yii2-admin looked nice to me, because it doesn't try to do anything other than rbac management. And I also liked the idea of ACF using "route" permissons.

But, I wondered where I should handle authorization of the staff. Should I assign roles to staff in this yii2-auth module, or in my user management module?

yii2-auth already had "assignment/index" and "assignment/view" pages. But they could only show the "staff_no". I wanted to show the full name and other information. That's why I introduced "fullnameField" and "extraColumns" into the assignment controller. You had already introduced the "searchModel", but it's not very useful without allowing extra columns displayed in the grid view.

Althogh I was satisfied with the result of the enhancement on yii2-auth, I also noted that I need to add some auth related functionalities. For example, I wanted to list all the staff with a certain role in a grid view. Also I wanted to assign/revoke a certain role to a group of staff in a batch mode. I decided to do it in my user management module, because I didn't want to stuff yii2-admn with those things that might be application specific.

**Comment by mdmunir** [comment]
I am OK with this fiture.
Is it tested well?

**Comment by softark** [comment]
Not tested throughly, but I don't see anything problematic.

**Pull request merged**
